/**
 * Copyright (c) 2019 Burst Apps Team
 * Modified Work (c) 2022 Signum Network
 */

import {ContractData} from '../contractData';

/**
 * The argument object for [[generateMethodCall]]
 *
 * @param {string} methodHash The signed long hash for the method generated by BlockTalk compiler
 * @param {ContractData[]} methodArgs Optional argument list for the method. Currently, up to three args are supported
 * @module contracts
 */
export interface GenerateMethodCallArgs {
    methodHash: string;
    methodArgs?: ContractData[];
}
