/**
 * Copyright (c) 2019 Burst Apps Team
 * Modified Work (c) 2022 Signum Network
 */

import {ContractData} from '../contractData';

/**
 * The argument object for {@link generateMethodCall}
 *
 * @param {string} methodId The signed long hash for the method generated by BlockTalk compiler
 * @param {ContractData[]} methodArgs Optional argument list for the method.
 * The arguments must be numerical, and cannot be alphanumeric. To convert a short text (max 8 chars/bytes) into a numerical representation
 * use {@link convertShortStringToContractData}
 * 
 */
export interface GenerateMethodCallArgs {
    methodId: string;
    methodArgs?: ContractData[];
}
